import 'package:pricing_structure/models/pricing_calc_model.dart';

const gridName = [
  "Pricing Calculator",
  "No. of Dev Resources",
  "Margins",
  "Initial Sales Rate Total cost w/ Overheads",
  "Automatic Calc with % discount",
  "Automatic Calc- 10,000 Differences",
  "Manual Calculator(User Inputs)",
];

final pricingCalItem = [
  PricingCal(
    role: "BE1",
    resources: "Aslam Hossain",
    externalRate: 65,
    noOfDays: 4,
    levelOfEffort: 100,
    totalPrice: 4300,
  ),
  PricingCal(
    role: "BE2",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "BE3",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "FE1",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "FE2",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "FE3",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "FS1",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "FS2",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "PDM/BA1",
    resources: "Sayed Afnaf Bhakt",
    externalRate: 100,
    noOfDays: 4,
    levelOfEffort: 25,
    totalPrice: 100,
  ),
  PricingCal(
    role: "PDM/BA2",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "QA",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "UX",
    resources: "Unused",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 0,
    totalPrice: 0,
  ),
  PricingCal(
    role: "MOCH Commision",
    resources: "Overhead-Swiss Team",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 20,
    totalPrice: 0,
  ),
  PricingCal(
    role: "Manual Resource",
    resources: "Manual Resource Name",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 20,
    totalPrice: 0,
  ),
  PricingCal(
    role: "Manual Resource",
    resources: "Manual Resource Name",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 20,
    totalPrice: 0,
  ),
  PricingCal(
    role: "Manual Resource",
    resources: "Manual Resource Name",
    externalRate: 0,
    noOfDays: 0,
    levelOfEffort: 20,
    totalPrice: 0,
  ),
];
